/**
 * Vellum QA acceptance matrix v1.
 *
 * Every case has: preconditions, steps, expected, verificationSources,
 * automation, evidence. Adding a ScreenId in src/screens/registry.ts requires
 * new cases here in the same change — tests/qa-matrix.test.ts enforces it.
 *
 * Verdict vocabulary is only PASS / FAIL / BLOCKED / NOT_RUN.
 * macOS is excluded from this round's pass claim.
 * Official live traffic is NOT_RUN this round (offline contract + routing isolation only).
 */

export const MATRIX_VERSION = "v1";

export const VERDICTS = Object.freeze(["PASS", "FAIL", "BLOCKED", "NOT_RUN"]);

/** ScreenId values from src/screens/registry.ts — keep in lockstep. */
export const REQUIRED_TABS = Object.freeze([
  "today",
  "models",
  "context",
  "enhanced",
  "remote",
  "log",
  "settings",
]);

export const REQUIRED_SURFACES = Object.freeze([
  ...REQUIRED_TABS,
  "onboarding",
  "dialog",
  "tray",
]);

export const REQUIRED_DOMAINS = Object.freeze([
  "tabs",
  "information-correctness",
  "enhanced-core",
  "enhanced-traits",
  "remote-manager",
  "subagents",
  "guardian-review",
  "offline-contracts",
]);

export const PASS_CLAIM = Object.freeze({
  platforms: ["windows"],
  excludePlatforms: ["macos"],
  officialLive: "NOT_RUN",
  tabSyncRule:
    "Any new ScreenId in src/screens/registry.ts must add matrix cases covering every new button, setting, and important display field in the same change. tests/qa-matrix.test.ts fails if a ScreenId has no cases.",
});

const CASE_KEYS = [
  "id",
  "domain",
  "surface",
  "lane",
  "necessary",
  "preconditions",
  "steps",
  "expected",
  "verificationSources",
  "automation",
  "evidence",
];

function c(spec) {
  for (const key of CASE_KEYS) {
    if (spec[key] === undefined || spec[key] === null || spec[key] === "") {
      throw new Error(`matrix case missing ${key}: ${spec.id ?? "?"}`);
    }
  }
  if (!REQUIRED_DOMAINS.includes(spec.domain)) {
    throw new Error(`unknown domain ${spec.domain} on ${spec.id}`);
  }
  return Object.freeze({
    macosInPassClaim: false,
    officialLive: false,
    ...spec,
  });
}

export const TAB_CONTROL = Object.freeze({
  today: "現況",
  models: "模型",
  context: "上下文",
  enhanced: "Enhanced Core",
  remote: "遠端",
  log: "紀錄",
  settings: "設定",
  onboarding: "開始",
  dialog: "取消",
  tray: "顯示 Vellum",
});

function tab(surface, id, fields) {
  const docker = fields.automation === "docker-dev-host";
  return c({
    domain: "tabs",
    surface,
    lane: "desktop",
    necessary: true,
    automation: "desktop-ui",
    verificationSources: ["ui", "backend-invoke", "reload"],
    control: TAB_CONTROL[surface],
    evidence: docker
      ? ["deploy-log.txt", "events.json"]
      : [`screenshots/${surface}-${id}.png`, "events.json"],
    ...fields,
    id: `tab.${surface}.${id}`,
  });
}

const TABS = [
  tab("today", "navigate", {
    preconditions: "正式 Windows release 桌面已啟動，測試帳戶已完成 onboarding。",
    steps: "點導覽「現況」。",
    expected: "畫布標題與 Proxy／額度／工作階段區塊可見，無空白錯誤頁。",
  }),
  tab("today", "proxy-start", {
    preconditions: "Proxy 未在跑。",
    steps: "按「啟動 Proxy」。",
    expected: "按鈕改為停止／還原文案；後端 proxy.running 為 true；程序存在。",
    verificationSources: ["ui", "get_proxy_status", "process-list"],
    control: "啟動 Proxy",
  }),
  tab("today", "proxy-stop-restore", {
    preconditions: "Proxy 正在跑。",
    steps: "按停止並還原 Codex。",
    expected: "Proxy 停止；Codex 設定還原；畫面與後端一致。取消不適用（此鈕無確認框）。",
    verificationSources: ["ui", "get_proxy_status", "codex-config"],
    control: "停止 Proxy 並還原 Codex",
  }),
  tab("today", "add-provider", {
    preconditions: "尚無啟用路線。",
    steps: "按「新增供應商」。",
    expected: "導向模型頁，可開始新增流程。",
    control: "加入供應商",
  }),
  tab("today", "quota-display", {
    preconditions: "至少一個支援額度的 Provider。",
    steps: "讀取週額度剩餘與緊繃 Provider 卡。",
    expected: "數字與 get_provider_overviews／quota snapshot 一致；不把估算用量標成官方額度。",
    verificationSources: ["ui", "quota-api", "provider-overview"],
  }),
  tab("today", "quota-refresh", {
    preconditions: "Provider 卡顯示可查額度。",
    steps: "按該列重新整理額度。",
    expected: "askedAt 更新；失敗時顯示 quotaFailed 而非靜默舊值。",
  }),
  tab("today", "context-meter", {
    preconditions: "有活躍或近期 session。",
    steps: "讀取上下文用量條與門檻標記。",
    expected: "used/window 與 list_sessions 或 context budget 一致。",
    verificationSources: ["ui", "list_sessions", "context-budget"],
  }),
  tab("today", "sessions-list", {
    preconditions: "有多個工作階段。",
    steps: "檢視前十個工作階段列與托盤收合。",
    expected: "活躍者在前；標籤、百分比與後端 session 紀錄一致。",
  }),
  tab("today", "findings-adjust-context", {
    preconditions: "現況頁出現上下文 finding。",
    steps: "按調整上下文。",
    expected: "導向上下文頁且選中對應 session。",
    control: "調整上下文視窗",
  }),
  tab("today", "statusbar-refresh", {
    preconditions: "桌面已開。",
    steps: "按狀態列重新整理。",
    expected: "狀態列與各頁資料重載；失敗顯示錯誤字串。",
    control: "重新整理",
  }),
  tab("today", "reload-after-save", {
    preconditions: "已變更儀表板可見供應商。",
    steps: "重新整理現況頁。",
    expected: "可見供應商集合與 localStorage／設定一致。",
  }),

  tab("models", "navigate", {
    preconditions: "正式桌面已啟動。",
    steps: "點導覽「模型」。",
    expected: "供應商列、模型選單與新增區可見。",
  }),
  tab("models", "select-route", {
    preconditions: "至少兩條已啟用路線。",
    steps: "選另一條為預設。",
    expected: "select_route 成功；現況頁標題模型跟著變；重載後仍是新選擇。",
  }),
  tab("models", "toggle-enabled", {
    preconditions: "一條非預設路線已啟用。",
    steps: "停用再啟用。",
    expected: "set_route_enabled 反映到清單與重載；停用路線不可被選為預設。",
  }),
  tab("models", "add-provider-probe", {
    preconditions: "測試 endpoint 與金鑰可用（或故意錯的 URL）。",
    steps: "填 URL／金鑰並探測。",
    expected: "成功列出相容模型；失敗顯示 probe 錯誤，不建立路線。",
  }),
  tab("models", "add-provider-save", {
    preconditions: "探測成功且已勾選模型。",
    steps: "儲存供應商。",
    expected: "新路線出現在清單與後端 list_routes；重載仍在。",
  }),
  tab("models", "add-provider-cancel", {
    preconditions: "探測表單已填。",
    steps: "取消／關閉新增流程。",
    expected: "不新增路線；list_routes 與操作前相同。",
  }),
  tab("models", "add-provider-error", {
    preconditions: "不可達 URL。",
    steps: "探測。",
    expected: "reachable=false 的錯誤文案；無新路線。",
  }),
  tab("models", "oauth-start", {
    preconditions: "ChatGPT 帳號流程可開（測試帳戶）。",
    steps: "開始 Codex OAuth。",
    expected: "顯示 user code 與驗證 URI；後端有 pending login。",
    automation: "desktop-ui-manual-checkpoint",
  }),
  tab("models", "oauth-cancel", {
    preconditions: "OAuth 進行中。",
    steps: "取消登入。",
    expected: "pending 消失；未寫入帳號。",
  }),
  tab("models", "oauth-refresh", {
    preconditions: "已有 ChatGPT 帳號。",
    steps: "重新整理帳號。",
    expected: "額度／帳號狀態更新或明確失敗。",
  }),
  tab("models", "logout-confirm", {
    preconditions: "已登入 ChatGPT。",
    steps: "登出全部 → 確認對話框確認。",
    expected: "帳號清除；重載後未登入。",
  }),
  tab("models", "logout-cancel", {
    preconditions: "已登入 ChatGPT，確認框開啟。",
    steps: "按取消。",
    expected: "帳號仍在；無 logout 副作用。",
  }),
  tab("models", "grok-start", {
    preconditions: "Grok 登入可用。",
    steps: "開始 Grok 帳號登入。",
    expected: "進入 waiting；可完成或取消。",
    automation: "desktop-ui-manual-checkpoint",
  }),
  tab("models", "grok-cancel", {
    preconditions: "Grok 登入 waiting。",
    steps: "取消。",
    expected: "poll 結束；未新增帳號。",
  }),
  tab("models", "route-rename-save", {
    preconditions: "既有自訂路線。",
    steps: "改名並儲存。",
    expected: "名稱寫入後端；重載仍是新名。",
  }),
  tab("models", "route-rename-cancel", {
    preconditions: "改名輸入中。",
    steps: "取消。",
    expected: "名稱不變。",
  }),
  tab("models", "route-reprobe", {
    preconditions: "既有自訂路線。",
    steps: "重新探測。",
    expected: "能力表更新或顯示錯誤；不刪除路線。",
  }),
  tab("models", "route-delete-confirm", {
    preconditions: "可刪的自訂路線。",
    steps: "刪除 → 確認。",
    expected: "路線消失；重載仍無。",
  }),
  tab("models", "catalog-rename", {
    preconditions: "模型選單有可改名項目。",
    steps: "改顯示名並儲存。",
    expected: "選單顯示新名；重載保留。",
  }),
  tab("models", "effort-save", {
    preconditions: "模型支援 effort。",
    steps: "改 effort 並套用。",
    expected: "後端模型設定更新；重載一致。",
  }),

  tab("context", "navigate", {
    preconditions: "正式桌面已啟動。",
    steps: "點導覽「上下文」。",
    expected: "工作階段清單與壓縮預覽區可見。此頁只讀。",
  }),
  tab("context", "session-select", {
    preconditions: "至少一個 Enhanced session。",
    steps: "點選清單中的對話。",
    expected: "標題、用量條、門檻與後端該 session 一致。",
    verificationSources: ["ui", "list_sessions", "compaction-preview"],
  }),
  tab("context", "session-search", {
    preconditions: "多個 session。",
    steps: "輸入搜尋字串。",
    expected: "清單過濾；已選明細不因搜尋被清掉。",
  }),
  tab("context", "preview-segments", {
    preconditions: "選中的 session 有壓縮預覽。",
    steps: "讀取壓縮前／後分段。",
    expected: "分段 token 加總與預覽 API 一致。",
  }),
  tab("context", "transcript", {
    preconditions: "該 session 有壓縮原文。",
    steps: "讀取送出指示與模型回寫。",
    expected: "原文與 compaction transcript API 相符，不是 UI 自己編的摘要。",
  }),
  tab("context", "empty", {
    preconditions: "無 Enhanced session。",
    steps: "開啟上下文頁。",
    expected: "空狀態文案；無虛構數字。",
  }),

  tab("enhanced", "navigate", {
    preconditions: "正式桌面已啟動。",
    steps: "點導覽 Enhanced Core。",
    expected: "四節交接線與狀態句可見。",
  }),
  tab("enhanced", "seam-artifact", {
    preconditions: "release 含 pinned core／bridge。",
    steps: "讀取「元件驗證」節。",
    expected: "artifactReady 與磁碟雜湊／lockfile 一致。",
    verificationSources: ["ui", "enhanced-runtime-status", "enhanced-runtime.lock.json"],
  }),
  tab("enhanced", "seam-armed", {
    preconditions: "Proxy 可啟動。",
    steps: "觀察路徑接管節。",
    expected: "environmentState leased 時與 CODEX_CLI_PATH 租約一致。",
  }),
  tab("enhanced", "seam-adopted", {
    preconditions: "Codex Desktop 曾啟動 bridge。",
    steps: "觀察 Bridge 對接節。",
    expected: "bridgeObserved 與實際 bridge 程序一致。",
    verificationSources: ["ui", "process-list", "enhanced-runtime-status"],
  }),
  tab("enhanced", "seam-in-place", {
    preconditions: "Enhanced 正在服務。",
    steps: "觀察執行確認節與頁首 serving 句。",
    expected: "active／serving 不與「舊啟動仍在服務」混淆。",
  }),
  tab("enhanced", "recheck", {
    preconditions: "Enhanced 頁已開。",
    steps: "按重新檢查相容性。",
    expected: "相容性結果更新；匯出路徑不變。",
    control: "重新檢查相容性",
  }),
  tab("enhanced", "export", {
    preconditions: "Enhanced 頁已開。",
    steps: "按匯出診斷。",
    expected: "寫出診斷檔；路徑顯示在頁面。",
    evidence: ["screenshots/enhanced-export.png", "diagnostics-export-path.txt"],
    control: "匯出診斷",
  }),
  tab("enhanced", "sessions", {
    preconditions: "有觀測到的 Enhanced session。",
    steps: "讀取工作階段列。",
    expected: "session id／狀態與 runtime observations 一致。",
  }),
  tab("enhanced", "blockers", {
    preconditions: "存在阻擋或未驗證差異。",
    steps: "讀取停止原因／差異列。",
    expected: "文案來自後端 blockers／protocol deltas，不是前端猜測。",
  }),

  tab("remote", "navigate", {
    preconditions: "正式桌面已啟動。",
    steps: "點導覽「遠端」。",
    expected: "主機清單與工作面狀態機可見。",
  }),
  tab("remote", "discover", {
    preconditions: "本機有 SSH 設定或 Docker dev host。",
    steps: "重新整理／探索主機。",
    expected: "候選主機與 discover API 一致；失敗有錯誤。",
  }),
  tab("remote", "select-host", {
    preconditions: "至少一台候選。",
    steps: "選一台。",
    expected: "工作面切到該主機狀態；inspect 資料對得上。",
  }),
  tab("remote", "plan", {
    preconditions: "已選主機且 release payload 就緒。",
    steps: "產生部署計畫。",
    expected: "計畫含模型／映像身分；與 planRemoteDeployment 回傳一致。",
  }),
  tab("remote", "apply", {
    preconditions: "有效計畫。",
    steps: "套用部署。",
    expected: "操作進度結束為成功或明確失敗；設定雜湊寫入主機。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "bootstrap-confirm", {
    preconditions: "待部署主機，確認框開啟。",
    steps: "確認部署。",
    expected: "開始 bootstrap 操作。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "bootstrap-cancel", {
    preconditions: "確認框開啟。",
    steps: "取消。",
    expected: "不啟動操作；主機狀態不變。",
  }),
  tab("remote", "restore-confirm", {
    preconditions: "已部署主機。",
    steps: "還原 → 確認（含 gate 若有）。",
    expected: "執行 restore；危險操作有確認。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "restore-cancel", {
    preconditions: "還原確認框開啟。",
    steps: "取消。",
    expected: "主機維持原狀。",
  }),
  tab("remote", "stop-app-owned", {
    preconditions: "遠端有 app-owned Codex。",
    steps: "停止 app-owned。",
    expected: "該程序停止；原生 daemon 權責不變。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "retry", {
    preconditions: "上一次操作失敗。",
    steps: "重試。",
    expected: "新操作 id；舊失敗仍可在紀錄中查到。",
  }),
  tab("remote", "bundle", {
    preconditions: "已選主機。",
    steps: "匯出診斷包。",
    expected: "產生檔案路徑；內容去敏。",
  }),
  tab("remote", "chatgpt-pair", {
    preconditions: "主機需要 ChatGPT pairing。",
    steps: "開始配對。",
    expected: "顯示配對狀態；可完成或取消。",
    automation: "desktop-ui-manual-checkpoint",
  }),
  tab("remote", "chatgpt-activate", {
    preconditions: "已有可啟用帳號。",
    steps: "啟用。",
    expected: "遠端帳號切換成功。",
  }),
  tab("remote", "chatgpt-skip", {
    preconditions: "配對步驟可跳過。",
    steps: "跳過。",
    expected: "流程前進且不假裝已配對。",
  }),
  tab("remote", "grok-login", {
    preconditions: "遠端 Grok 登入可用。",
    steps: "開始登入。",
    expected: "waiting 狀態可觀察。",
    automation: "desktop-ui-manual-checkpoint",
  }),
  tab("remote", "grok-cancel", {
    preconditions: "遠端 Grok waiting。",
    steps: "取消。",
    expected: "登入中止。",
  }),
  tab("remote", "grok-refresh", {
    preconditions: "遠端已有 Grok 狀態。",
    steps: "重新整理。",
    expected: "狀態更新或錯誤。",
  }),
  tab("remote", "device-pair", {
    preconditions: "ChatGPT 已同步。",
    steps: "配對行動裝置。",
    expected: "pairing payload 出現；未同步時按鈕停用。",
  }),
  tab("remote", "execution-add", {
    preconditions: "可新增 Official execution 帳號。",
    steps: "填名稱並新增。",
    expected: "帳號列出現或登入流程開始。",
  }),
  tab("remote", "execution-select", {
    preconditions: "至少兩個 execution 帳號。",
    steps: "選另一個。",
    expected: "選中標記與後端一致。",
  }),
  tab("remote", "execution-remove", {
    preconditions: "可刪帳號。",
    steps: "移除。",
    expected: "列表與後端不再包含該帳號。",
  }),
  tab("remote", "install-codex", {
    preconditions: "release 就緒、主機缺 Codex。",
    steps: "安裝 Codex → 確認。",
    expected: "遠端 Codex 版本與相容性狀態更新。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "update-agent", {
    preconditions: "Agent 可更新。",
    steps: "更新 Agent → 確認。",
    expected: "agentVersion 變更或明確 no-op。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "repair", {
    preconditions: "設定漂移。",
    steps: "修復。",
    expected: "configuration.state 回到 current。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "restart-native", {
    preconditions: "原生 daemon 在跑。",
    steps: "重啟原生 → 確認。",
    expected: "daemon 仍為 codexCliDaemon 權責，broker 不是 session authority。",
    lane: "remote",
    automation: "docker-dev-host",
  }),
  tab("remote", "ssh-trust-confirm", {
    preconditions: "未信任指紋。",
    steps: "確認指紋。",
    expected: "後續 SSH 操作可進行。",
  }),
  tab("remote", "ssh-trust-cancel", {
    preconditions: "指紋確認框開啟。",
    steps: "取消。",
    expected: "不寫入信任；部署不開始。",
  }),
  tab("remote", "reapply-noop", {
    preconditions: "主機已與目前計畫一致。",
    steps: "再次套用／重複部署。",
    expected: "idempotent no-op；設定雜湊不變。",
    lane: "remote",
    automation: "docker-dev-host",
  }),

  tab("log", "navigate", {
    preconditions: "正式桌面已啟動。",
    steps: "點導覽「紀錄」。",
    expected: "熱區圖與請求列表可見。",
  }),
  tab("log", "heatmap-mode", {
    preconditions: "有用量活動。",
    steps: "切換日／週／累計。",
    expected: "格陣重算；位置不變。",
  }),
  tab("log", "requests-page", {
    preconditions: "超過一頁請求。",
    steps: "下一頁／上一頁。",
    expected: "分頁邊界正確；不一次載入全窗。",
  }),
  tab("log", "providers-segment", {
    preconditions: "多個 provider 有用量。",
    steps: "指到佔比段。",
    expected: "官方個人檔案用量與 proxy 逐請求用量分開標示（fromProfile）。",
    verificationSources: ["ui", "usage-activity", "request-log"],
  }),
  tab("log", "subagent-summary", {
    preconditions: "有子代理回合。",
    steps: "讀取子代理摘要。",
    expected: "parent/child 列與後端 subagent runs 一致，無漏算或重複。",
  }),
  tab("log", "usage-official-vs-estimated", {
    preconditions: "同時有官方統計與第三方 proxy 用量。",
    steps: "對照熱區與請求列。",
    expected: "官方數字不與估算／逐請求加總混成同一欄。",
    verificationSources: ["ui", "codex-profile-usage", "proxy-request-log"],
  }),

  tab("settings", "navigate", {
    preconditions: "正式桌面已啟動。",
    steps: "點導覽「設定」。",
    expected: "審查、搜尋、子代理、還原、進階、結束分區可見。",
  }),
  tab("settings", "review-policy", {
    preconditions: "設定頁已開。",
    steps: "切換 always／failover。",
    expected: "policy 寫入後端；failover 才顯示備援欄。重載保留。",
  }),
  tab("settings", "review-route-model", {
    preconditions: "有可用審查模型。",
    steps: "改 route／model 並等待儲存。",
    expected: "get review settings 相符；儲存中忙碌態結束後無錯誤。",
  }),
  tab("settings", "review-save-reload", {
    preconditions: "剛改審查設定。",
    steps: "重載應用或重新整理。",
    expected: "設定仍在；佇列中的儲存不丟。",
  }),
  tab("settings", "websearch-toggle", {
    preconditions: "設定頁已開。",
    steps: "開關第三方網頁搜尋。",
    expected: "設定持久化；官方 Provider 不受影響（文案與後端一致）。",
  }),
  tab("settings", "websearch-key", {
    preconditions: "搜尋已開。",
    steps: "輸入 Brave 金鑰並儲存。",
    expected: "金鑰不以明文回顯；hasKey 為 true。",
  }),
  tab("settings", "websearch-probe", {
    preconditions: "已設金鑰。",
    steps: "執行搜尋連線測試。",
    expected: "成功筆數或失敗細節；probedAt 為本機詢問時間。",
  }),
  tab("settings", "websearch-domains", {
    preconditions: "搜尋已開。",
    steps: "編輯允許／封鎖清單並儲存。",
    expected: "重載後清單一致。",
  }),
  tab("settings", "websearch-unsaved-cancel", {
    preconditions: "網域草稿已改未存。",
    steps: "離開欄位不存（或重載）。",
    expected: "未存草稿不寫入後端。",
  }),
  tab("settings", "subagent-mode", {
    preconditions: "子代理能力已知。",
    steps: "切換子代理模式。",
    expected: "不支援時顯示 unsupported 且不假裝成功。",
  }),
  tab("settings", "subagent-model", {
    preconditions: "custom 模式被支援。",
    steps: "選子代理模型並儲存。",
    expected: "重載後模型 id 一致。",
  }),
  tab("settings", "locale", {
    preconditions: "語言選擇器啟用。",
    steps: "切換語言偏好。",
    expected: "文案切換；偏好持久化。未啟用時控制項不出現。",
  }),
  tab("settings", "dashboard-providers", {
    preconditions: "多條路線。",
    steps: "勾選／取消現況可見供應商。",
    expected: "現況頁供應商卡集合隨之改變並在重載後保留。",
  }),
  tab("settings", "restore-codex", {
    preconditions: "Codex 曾被 Vellum 管理。",
    steps: "還原 Codex。",
    expected: "cleared／preserved 列表與實際檔案操作一致。",
  }),
  tab("settings", "drain-toggle", {
    preconditions: "Proxy 在跑。",
    steps: "停止接新請求／恢復。",
    expected: "runtime.draining 與按鈕文案一致。",
  }),
  tab("settings", "restart-codex", {
    preconditions: "無進行中回合或允許重啟。",
    steps: "重啟 Codex。",
    expected: "notice 說明結果；失敗不假成功。",
  }),
  tab("settings", "restart-anyway", {
    preconditions: "有進行中回合導致重啟被擋。",
    steps: "仍要重啟。",
    expected: "出現 anyway 按鈕；執行後有結果。",
  }),
  tab("settings", "rollback-catalog", {
    preconditions: "有歷史模型選單版本。",
    steps: "回復某一版。",
    expected: "activeCatalogVersion 改變或明確錯誤。",
  }),
  tab("settings", "reopen-onboarding", {
    preconditions: "已完成 onboarding。",
    steps: "重開導覽。",
    expected: "進入 onboarding 畫面，可取消回到設定。",
  }),
  tab("settings", "exit", {
    preconditions: "桌面在跑。",
    steps: "結束 Vellum。",
    expected: "Proxy 停止、Codex 還原、行程退出。",
    automation: "desktop-ui-manual-checkpoint",
  }),
  tab("settings", "error-display", {
    preconditions: "後端暫時失敗（斷 API）。",
    steps: "觸發儲存或載入。",
    expected: "錯誤字串可見，狀態不標成已儲存。",
  }),
];

const ONBOARDING = [
  c({
    id: "onboarding.start",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "全新測試帳戶，localStorage 無完成旗標。",
    steps: "啟動應用。",
    expected: "出現犢皮紙 onboarding，而非主畫面。",
    verificationSources: ["ui", "localStorage"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-start.png"],
  }),
  c({
    id: "onboarding.step-next",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "onboarding 第一幕。",
    steps: "按開始／下一步。",
    expected: "進到連線幕；頁邊進度更新。",
    verificationSources: ["ui"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-step.png"],
  }),
  c({
    id: "onboarding.connect-chatgpt",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "連線幕。",
    steps: "連線 ChatGPT。",
    expected: "顯示 device code；完成後帳號列更新。",
    verificationSources: ["ui", "oauth-status"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["screenshots/onboarding-chatgpt.png", "events.json"],
  }),
  c({
    id: "onboarding.connect-chatgpt-cancel",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "ChatGPT pending code 顯示中。",
    steps: "取消。",
    expected: "pending 清除；無新帳號。",
    verificationSources: ["ui", "oauth-status"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-chatgpt-cancel.png"],
  }),
  c({
    id: "onboarding.connect-grok",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "連線幕。",
    steps: "連線 Grok。",
    expected: "進入 waiting；完成後帳號列更新。",
    verificationSources: ["ui", "grok-status"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["screenshots/onboarding-grok.png"],
  }),
  c({
    id: "onboarding.connect-grok-cancel",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "Grok waiting。",
    steps: "取消。",
    expected: "呼叫 cancel；無新帳號。",
    verificationSources: ["ui", "grok-status"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-grok-cancel.png"],
  }),
  c({
    id: "onboarding.connect-custom-save",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "可用的 Codex-compatible 自訂 endpoint。",
    steps: "填寫並新增。",
    expected: "探測成功後寫入路線；不相容協議被拒絕。",
    verificationSources: ["ui", "list_routes", "probe"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-custom.png", "routes.json"],
  }),
  c({
    id: "onboarding.connect-custom-error",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "壞的 URL。",
    steps: "新增自訂端點。",
    expected: "錯誤可見；無新路線。",
    verificationSources: ["ui", "list_routes"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-custom-error.png"],
  }),
  c({
    id: "onboarding.start-proxy",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "已有至少一條路線。",
    steps: "在最後幕啟動 Proxy。",
    expected: "Proxy running；可完成 onboarding。",
    verificationSources: ["ui", "get_proxy_status"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-proxy.png"],
  }),
  c({
    id: "onboarding.finish",
    domain: "tabs",
    surface: "onboarding",
    lane: "desktop",
    necessary: true,
    preconditions: "最後幕。",
    steps: "完成。",
    expected: "進入現況頁；完成旗標寫入；再啟動不再強迫導覽。",
    verificationSources: ["ui", "localStorage"],
    automation: "desktop-ui",
    evidence: ["screenshots/onboarding-finish.png"],
  }),
];

const DIALOGS = [
  c({
    id: "dialog.confirm-ok",
    domain: "tabs",
    surface: "dialog",
    lane: "desktop",
    necessary: true,
    preconditions: "任一 Confirm 開啟（例如刪除路線）。",
    steps: "按確認。",
    expected: "危險動作執行一次。",
    verificationSources: ["ui", "backend-invoke"],
    automation: "desktop-ui",
    evidence: ["screenshots/dialog-ok.png", "events.json"],
  }),
  c({
    id: "dialog.confirm-cancel",
    domain: "tabs",
    surface: "dialog",
    lane: "desktop",
    necessary: true,
    preconditions: "Confirm 開啟。",
    steps: "按取消。",
    expected: "動作不執行。",
    verificationSources: ["ui", "backend-invoke"],
    automation: "desktop-ui",
    evidence: ["screenshots/dialog-cancel.png"],
  }),
  c({
    id: "dialog.confirm-esc",
    domain: "tabs",
    surface: "dialog",
    lane: "desktop",
    necessary: true,
    preconditions: "Confirm 開啟。",
    steps: "按 Esc。",
    expected: "等同取消。",
    verificationSources: ["ui"],
    automation: "desktop-ui",
    evidence: ["screenshots/dialog-esc.png"],
  }),
  c({
    id: "dialog.gate-blocked",
    domain: "tabs",
    surface: "dialog",
    lane: "desktop",
    necessary: true,
    preconditions: "含 gate 片語的危險確認（遠端還原等）。",
    steps: "不輸入或輸入錯誤片語。",
    expected: "確認鈕停用；動作不執行。",
    verificationSources: ["ui"],
    automation: "desktop-ui",
    evidence: ["screenshots/dialog-gate-blocked.png"],
  }),
  c({
    id: "dialog.gate-ok",
    domain: "tabs",
    surface: "dialog",
    lane: "desktop",
    necessary: true,
    preconditions: "gate 確認框。",
    steps: "輸入正確片語並確認。",
    expected: "動作執行。",
    verificationSources: ["ui", "backend-invoke"],
    automation: "desktop-ui",
    evidence: ["screenshots/dialog-gate-ok.png"],
  }),
];

const TRAY = [
  c({
    id: "tray.show",
    domain: "tabs",
    surface: "tray",
    lane: "desktop",
    necessary: true,
    preconditions: "視窗已隱藏、托盤圖示存在。",
    steps: "托盤選單「顯示 Vellum」。",
    expected: "主視窗恢復。",
    verificationSources: ["ui", "window-state"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["screenshots/tray-show.png"],
  }),
  c({
    id: "tray.toggle-proxy",
    domain: "tabs",
    surface: "tray",
    lane: "desktop",
    necessary: true,
    preconditions: "托盤選單可用。",
    steps: "「啟動／停止 Proxy」。",
    expected: "與現況頁同一後端狀態翻轉。",
    verificationSources: ["ui", "get_proxy_status"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["screenshots/tray-proxy.png", "proxy-status.json"],
  }),
  c({
    id: "tray.exit",
    domain: "tabs",
    surface: "tray",
    lane: "desktop",
    necessary: true,
    preconditions: "應用在跑。",
    steps: "「結束 Vellum」。",
    expected: "停止 Proxy、還原 Codex、行程退出。",
    verificationSources: ["process-list", "codex-config"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["events.json"],
  }),
  c({
    id: "tray.left-click-restore",
    domain: "tabs",
    surface: "tray",
    lane: "desktop",
    necessary: true,
    preconditions: "視窗隱藏。",
    steps: "左鍵點托盤圖示。",
    expected: "視窗恢復；右鍵不偷走選單。",
    verificationSources: ["ui"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["screenshots/tray-click.png"],
  }),
  c({
    id: "tray.close-hides-restore-codex",
    domain: "tabs",
    surface: "tray",
    lane: "desktop",
    necessary: true,
    preconditions: "Proxy 在跑、視窗可見。",
    steps: "按視窗關閉。",
    expected: "視窗隱藏而非結束行程；Proxy 停止且 Codex 還原（關閉是 data-plane stop）。",
    verificationSources: ["window-state", "get_proxy_status", "codex-config"],
    automation: "desktop-ui-manual-checkpoint",
    evidence: ["screenshots/tray-close.png", "proxy-status.json"],
  }),
];

const INFO = [
  c({
    id: "info.model-vs-catalog",
    domain: "information-correctness",
    surface: "models",
    lane: "desktop",
    necessary: true,
    preconditions: "已載入模型選單。",
    steps: "對照 UI 模型 id／名稱與 list_model_routes／catalog。",
    expected: "一致；不能只比畫面與同一份 mock。",
    verificationSources: ["ui", "list_model_routes", "catalog-file"],
    automation: "desktop-ui",
    evidence: ["screenshots/info-models.png", "catalog-snapshot.json"],
  }),
  c({
    id: "info.connection-vs-process",
    domain: "information-correctness",
    surface: "today",
    lane: "desktop",
    necessary: true,
    preconditions: "Proxy 曾啟動。",
    steps: "對照 UI 連線狀態、get_proxy_status、本機監聽埠與行程。",
    expected: "三者一致；停止後埠與行程消失。",
    verificationSources: ["ui", "get_proxy_status", "netstat", "process-list"],
    automation: "desktop-ui",
    evidence: ["proxy-status.json", "process.txt"],
  }),
  c({
    id: "info.runtime-vs-backend",
    domain: "information-correctness",
    surface: "enhanced",
    lane: "desktop",
    necessary: true,
    preconditions: "Enhanced 狀態可讀。",
    steps: "對照狀態列／Enhanced 頁與 enhanced-runtime-status。",
    expected: "serving／ready／digest 一致。",
    verificationSources: ["ui", "enhanced-runtime-status", "lockfile"],
    automation: "desktop-ui",
    evidence: ["runtime-status.json"],
  }),
  c({
    id: "info.session-vs-backend",
    domain: "information-correctness",
    surface: "context",
    lane: "desktop",
    necessary: true,
    preconditions: "有 session。",
    steps: "對照現況／上下文／紀錄的 session id。",
    expected: "同一 id 三頁一致，並等於 list_sessions。",
    verificationSources: ["ui", "list_sessions"],
    automation: "desktop-ui",
    evidence: ["sessions.json"],
  }),
  c({
    id: "info.usage-provider-vs-estimated",
    domain: "information-correctness",
    surface: "log",
    lane: "desktop",
    necessary: true,
    preconditions: "有官方與第三方用量。",
    steps: "對照 UI 標示與 request log／profile usage。",
    expected: "provider-reported 與估算分欄；不得把估算標成官方。",
    verificationSources: ["ui", "usage-activity", "request-log"],
    automation: "desktop-ui",
    evidence: ["usage.json", "screenshots/info-usage.png"],
  }),
  c({
    id: "info.log-vs-events",
    domain: "information-correctness",
    surface: "log",
    lane: "desktop",
    necessary: true,
    preconditions: "剛發生一筆真實請求或失敗。",
    steps: "對照紀錄列與實際事件時間、狀態碼、模型。",
    expected: "與 get_request_log／boot telemetry 相符。",
    verificationSources: ["ui", "request-log", "real-event"],
    automation: "desktop-ui",
    evidence: ["request-log.json"],
  }),
];

const ENHANCED_CORE = [
  c({
    id: "enhanced.core.read-file",
    domain: "enhanced-core",
    surface: "enhanced",
    lane: "live",
    necessary: true,
    preconditions: "正式桌面、pinned Enhanced Core、第三方 session、測試 workspace。原生與 Enhanced 共用有效 Codex home。",
    steps: "請模型讀取測試檔。",
    expected: "工具讀到真實檔案內容；runtime attestation 顯示 pinned core。",
    verificationSources: ["session-events", "file", "attestation"],
    automation: "live-session",
    evidence: ["attestation.json", "tool-events.json", "session-id.txt"],
    models: ["opencode-mimo-2.5", "grok-4.6", "qwen"],
  }),
  c({
    id: "enhanced.core.edit-function",
    domain: "enhanced-core",
    surface: "enhanced",
    lane: "live",
    necessary: true,
    preconditions: "同上；測試檔含一個小函式。",
    steps: "請模型修改該函式（簡單、可客觀判定）。",
    expected: "磁碟檔案變更符合要求；不是只在對話裡宣稱。",
    verificationSources: ["file-diff", "tool-events"],
    automation: "live-session",
    evidence: ["file-before.txt", "file-after.txt", "tool-events.json"],
    models: ["opencode-mimo-2.5", "grok-4.6", "qwen"],
  }),
  c({
    id: "enhanced.core.run-tests",
    domain: "enhanced-core",
    surface: "enhanced",
    lane: "live",
    necessary: true,
    preconditions: "測試 workspace 有一個會過的小測試。",
    steps: "請模型執行測試。",
    expected: "實際 runner 輸出進入工具事件；exit 成功。",
    verificationSources: ["tool-events", "test-output"],
    automation: "live-session",
    evidence: ["test-output.txt", "tool-events.json"],
    models: ["opencode-mimo-2.5", "grok-4.6", "qwen"],
  }),
  c({
    id: "enhanced.core.continue",
    domain: "enhanced-core",
    surface: "enhanced",
    lane: "live",
    necessary: true,
    preconditions: "同一 session 已完成前一步。",
    steps: "續聊，引用先前檔案變更。",
    expected: "模型看得到先前工具結果；session id 不變。",
    verificationSources: ["session-id", "events"],
    automation: "live-session",
    evidence: ["session-id.txt", "continue-events.json"],
    models: ["opencode-mimo-2.5", "grok-4.6", "qwen"],
  }),
  c({
    id: "enhanced.core.cancel",
    domain: "enhanced-core",
    surface: "enhanced",
    lane: "live",
    necessary: true,
    preconditions: "長工具回合進行中。",
    steps: "取消。",
    expected: "取消優先於續行；無額外成功完成事件。",
    verificationSources: ["events", "process"],
    automation: "live-session",
    evidence: ["cancel-events.json"],
    models: ["opencode-mimo-2.5", "grok-4.6", "qwen"],
  }),
  c({
    id: "enhanced.core.attestation-pin",
    domain: "enhanced-core",
    surface: "enhanced",
    lane: "live",
    necessary: true,
    preconditions: "上述任一成功 session。",
    steps: "保存 attestation、provider／model、digest。",
    expected: "digest 等於 enhanced-runtime.lock.json 目前平台 artifactSha256。",
    verificationSources: ["attestation", "lockfile"],
    automation: "live-session",
    evidence: ["attestation.json", "lockfile-pin.json"],
  }),
];

function trait(id, lane, automation, extra) {
  return c({
    id: `enhanced.trait.${id}.${lane}`,
    domain: "enhanced-traits",
    surface: "enhanced",
    lane,
    necessary: true,
    automation,
    ...extra,
  });
}

const ENHANCED_TRAITS = [
  trait("tool-repeat", "offline", "offline-inject", {
    preconditions: "離線注入重複工具呼叫的 transcript。",
    steps: "重放／注入。",
    expected: "重複工具被抑制或合併，有結構化證據。",
    verificationSources: ["unit-or-replay", "diagnostics"],
    evidence: ["replay.json"],
  }),
  trait("tool-repeat", "live", "live-session", {
    preconditions: "真實模型、可誘發重複工具的簡單任務。",
    steps: "觀察工具事件。",
    expected: "若未觀察到該特性，標 NOT_RUN／未驗證，不得 live-PASS。",
    verificationSources: ["tool-events"],
    evidence: ["tool-events.json"],
    unobservedMeans: "NOT_RUN",
  }),
  trait("context-recovery", "offline", "offline-inject", {
    preconditions: "離線注入可恢復的上下文缺口。",
    steps: "跑 Enhanced context recovery 路徑。",
    expected: "恢復行為有測試證據。",
    verificationSources: ["crate-tests", "replay"],
    evidence: ["recovery-offline.json"],
  }),
  trait("context-recovery", "live", "live-session", {
    preconditions: "真實 session 出現需恢復的上下文。",
    steps: "觀察恢復。",
    expected: "有事件才可 live-PASS；否則 NOT_RUN。",
    verificationSources: ["events"],
    evidence: ["recovery-live.json"],
    unobservedMeans: "NOT_RUN",
  }),
  trait("continuation", "offline", "offline-inject", {
    preconditions: "離線契約／replay 含有限次續行。",
    steps: "重放 continuation。",
    expected: "續行次數有上限；契約測試通過。",
    verificationSources: ["protocol-replay", "proxy-runtime-tests"],
    evidence: ["continuation-offline.json"],
  }),
  trait("continuation", "live", "live-session", {
    preconditions: "真實模型觸發續行。",
    steps: "觀察續行次數與完成。",
    expected: "有限次；未觀察到則 NOT_RUN。",
    verificationSources: ["events"],
    evidence: ["continuation-live.json"],
    unobservedMeans: "NOT_RUN",
  }),
  trait("cancel-priority", "offline", "offline-inject", {
    preconditions: "離線取消注入。",
    steps: "在續行窗口取消。",
    expected: "取消優先，無成功空結果。",
    verificationSources: ["unit-or-replay"],
    evidence: ["cancel-offline.json"],
  }),
  trait("cancel-priority", "live", "live-session", {
    preconditions: "真實進行中回合。",
    steps: "取消。",
    expected: "取消生效；未觀察到不得 live-PASS。",
    verificationSources: ["events"],
    evidence: ["cancel-live.json"],
    unobservedMeans: "NOT_RUN",
  }),
];

const REMOTE_MANAGER = [
  c({
    id: "remote.deploy.clean-host",
    domain: "remote-manager",
    surface: "remote",
    lane: "remote",
    necessary: true,
    preconditions: "獨立命名的 Docker dev host，乾淨狀態；走正式部署流程（scripts/dev-host.ps1 + remote-e2e full／Desktop 部署）。",
    steps: "從乾淨 host 安裝。",
    expected: "Agent／原生 App Server 路徑起來；不用舊 Broker 充當現行架構。",
    verificationSources: ["docker", "agent-status", "readyz"],
    automation: "docker-dev-host",
    evidence: ["deploy-log.txt", "readyz.json", "agent-status.json"],
  }),
  c({
    id: "remote.deploy.health",
    domain: "remote-manager",
    surface: "remote",
    lane: "remote",
    necessary: true,
    preconditions: "部署完成。",
    steps: "查健康。",
    expected: "dockerAvailable、proxy ready、nativeCodex.daemonOwner=codexCliDaemon。",
    verificationSources: ["readyz", "agent-status"],
    automation: "docker-dev-host",
    evidence: ["health.json"],
  }),
  c({
    id: "remote.deploy.config-consistency",
    domain: "remote-manager",
    surface: "remote",
    lane: "remote",
    necessary: true,
    preconditions: "部署完成。",
    steps: "比對 Desktop 計畫與主機 configuration hash。",
    expected: "一致。",
    verificationSources: ["plan", "host-config"],
    automation: "docker-dev-host",
    evidence: ["config-hash.json"],
  }),
  c({
    id: "remote.deploy.reapply-noop",
    domain: "remote-manager",
    surface: "remote",
    lane: "remote",
    necessary: true,
    preconditions: "已與計畫一致。",
    steps: "重複部署。",
    expected: "idempotent no-op。",
    verificationSources: ["operation-log", "config-hash"],
    automation: "docker-dev-host",
    evidence: ["reapply.json"],
  }),
  c({
    id: "remote.deploy.reconnect",
    domain: "remote-manager",
    surface: "remote",
    lane: "remote",
    necessary: true,
    preconditions: "健康的 host。",
    steps: "中斷再重連控制通道。",
    expected: "重連後狀態恢復；session authority 仍是原生 daemon。",
    verificationSources: ["agent-status", "events"],
    automation: "docker-dev-host",
    evidence: ["reconnect.json"],
  }),
  c({
    id: "remote.deploy.stop-cleanup",
    domain: "remote-manager",
    surface: "remote",
    lane: "remote",
    necessary: true,
    preconditions: "獨立命名資源。",
    steps: "停止並清理。",
    expected: "容器／網路以該測試前綴消失；清理失敗要 FAIL。",
    verificationSources: ["docker", "dev-host.ps1 down"],
    automation: "docker-dev-host",
    evidence: ["cleanup.log"],
  }),
  c({
    id: "remote.session.tool-task",
    domain: "remote-manager",
    surface: "remote",
    lane: "live",
    necessary: true,
    preconditions: "部署後原生 Agent／App Server 可用。",
    steps: "建立真實 session 並完成簡單工具任務。",
    expected: "工具結果在遠端 workspace；非 Broker 測試。",
    verificationSources: ["app-server-events", "workspace-files"],
    automation: "live-session",
    evidence: ["remote-session.json", "tool-events.json"],
  }),
  c({
    id: "remote.session.resume",
    domain: "remote-manager",
    surface: "remote",
    lane: "live",
    necessary: true,
    preconditions: "上一案例的 session id。",
    steps: "resume。",
    expected: "同一 thread 繼續；上下文仍在。",
    verificationSources: ["session-id", "events"],
    automation: "live-session",
    evidence: ["resume.json"],
  }),
];

const SUBAGENTS = [
  c({
    id: "subagent.spawn-two",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "真實 parent session；兩個簡單子任務（例如回傳固定標記）。",
    steps: "parent 派出兩個子代理。",
    expected: "兩個 child 身分可區分；路由正確。",
    verificationSources: ["spawn-events", "headers"],
    automation: "live-session",
    evidence: ["parent.json", "child-a.json", "child-b.json"],
  }),
  c({
    id: "subagent.message",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "兩個 child 已 spawn。",
    steps: "parent 傳訊息給 child。",
    expected: "訊息到達對應 child。",
    verificationSources: ["events"],
    automation: "live-session",
    evidence: ["message-events.json"],
  }),
  c({
    id: "subagent.wait",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "child 執行中。",
    steps: "parent wait。",
    expected: "等到完成或明確超時。",
    verificationSources: ["events"],
    automation: "live-session",
    evidence: ["wait-events.json"],
  }),
  c({
    id: "subagent.resume",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "child 可 resume。",
    steps: "resume child。",
    expected: "同一 child id 繼續。",
    verificationSources: ["events"],
    automation: "live-session",
    evidence: ["child-resume.json"],
  }),
  c({
    id: "subagent.close",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "child 仍開著。",
    steps: "close child。",
    expected: "child 結束；不再收訊息。",
    verificationSources: ["events"],
    automation: "live-session",
    evidence: ["close-events.json"],
  }),
  c({
    id: "subagent.complete",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "兩個簡單子任務。",
    steps: "等到完成。",
    expected: "回傳內容可客觀判定；parent 收到結果。",
    verificationSources: ["return-payload"],
    automation: "live-session",
    evidence: ["results.json"],
  }),
  c({
    id: "subagent.parent-cancel",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "parent 與 child 進行中。",
    steps: "取消父任務。",
    expected: "child 一併停；無幽靈計費回合。",
    verificationSources: ["events", "usage"],
    automation: "live-session",
    evidence: ["parent-cancel.json"],
  }),
  c({
    id: "subagent.usage-accounting",
    domain: "subagents",
    surface: "log",
    lane: "live",
    necessary: true,
    preconditions: "上述回合有 usage。",
    steps: "加總 parent＋child，對照 UI 與後端。",
    expected: "不漏算、不重複計數。",
    verificationSources: ["usage-activity", "request-log"],
    automation: "live-session",
    evidence: ["usage-rollups.json"],
  }),
];

const GUARDIAN = [
  c({
    id: "guardian.known-defect",
    domain: "guardian-review",
    surface: "settings",
    lane: "live",
    necessary: true,
    preconditions: "測試 workspace 含已知缺陷；審查走正式 production 路徑。",
    steps: "用正常操作觸發自動審查。",
    expected: "findings 指出該缺陷；模型身分、狀態、用量、政策結果都有。",
    verificationSources: ["review-run", "findings", "usage"],
    automation: "live-session",
    evidence: ["review-known-defect.json", "findings.json"],
  }),
  c({
    id: "guardian.clean-diff",
    domain: "guardian-review",
    surface: "settings",
    lane: "live",
    necessary: true,
    preconditions: "乾淨 diff。",
    steps: "觸發審查。",
    expected: "無虛構 finding；狀態成功但 findings 可為空。",
    verificationSources: ["review-run"],
    automation: "live-session",
    evidence: ["review-clean.json"],
  }),
  c({
    id: "guardian.findings-identity",
    domain: "guardian-review",
    surface: "settings",
    lane: "live",
    necessary: true,
    preconditions: "任一正式審查 run。",
    steps: "讀取模型身分與政策。",
    expected: "與設定的 review route／model／policy 一致。",
    verificationSources: ["review-settings", "review-run"],
    automation: "live-session",
    evidence: ["review-identity.json"],
  }),
  c({
    id: "guardian.fault.verify-fail",
    domain: "guardian-review",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "故障注入：驗證失敗。",
    steps: "跑審查路徑。",
    expected: "不得轉成成功空審查。",
    verificationSources: ["fault-inject", "review-status"],
    automation: "offline-inject",
    evidence: ["fault-verify-fail.json"],
  }),
  c({
    id: "guardian.fault.429",
    domain: "guardian-review",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "注入 429。",
    steps: "跑審查。",
    expected: "失敗類別保留 quota／rate-limit；非成功空審查。",
    verificationSources: ["fault-inject"],
    automation: "offline-inject",
    evidence: ["fault-429.json"],
  }),
  c({
    id: "guardian.fault.timeout",
    domain: "guardian-review",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "注入逾時。",
    steps: "跑審查。",
    expected: "review_attempt_timeout 或同等；非成功。",
    verificationSources: ["fault-inject"],
    automation: "offline-inject",
    evidence: ["fault-timeout.json"],
  }),
  c({
    id: "guardian.fault.malformed",
    domain: "guardian-review",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "注入格式錯誤回應。",
    steps: "跑審查。",
    expected: "格式錯誤失敗；非成功空審查。",
    verificationSources: ["fault-inject"],
    automation: "offline-inject",
    evidence: ["fault-malformed.json"],
  }),
];

const OFFLINE = [
  c({
    id: "offline.typecheck",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "工作樹可執行 pnpm。",
    steps: "pnpm typecheck",
    expected: "exit 0。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/typecheck.txt"],
  }),
  c({
    id: "offline.vitest",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "工作樹可執行 pnpm test。",
    steps: "pnpm test",
    expected: "Vitest 通過。renderer mock 只算回歸，不算 live。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/vitest.txt"],
  }),
  c({
    id: "offline.cargo-proxy-runtime",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "Rust toolchain。",
    steps: "cargo test -p vellum-proxy-runtime --lib",
    expected: "lib 測試通過。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/cargo-proxy-runtime.txt"],
  }),
  c({
    id: "offline.cargo-tauri-lib",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "Rust toolchain。",
    steps: "cargo test --manifest-path src-tauri/Cargo.toml --lib",
    expected: "通過。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/cargo-tauri-lib.txt"],
  }),
  c({
    id: "offline.cargo-contract",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "Rust toolchain。",
    steps: "cargo test --manifest-path src-tauri/Cargo.toml --test contract",
    expected: "通過。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/cargo-contract.txt"],
  }),
  c({
    id: "offline.protocol-replay",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "vellum-eval 可建。",
    steps: "vellum-eval protocol-replay",
    expected: "配額免費 protocol replay 通過。",
    verificationSources: ["command-log", "target/vellum-evals"],
    automation: "shell",
    evidence: ["logs/protocol-replay.txt"],
  }),
  c({
    id: "offline.app-replay-desktop",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "vellum-eval 可建。",
    steps: "app-replay --suite desktop-protocol-replay",
    expected: "通過。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/app-replay-desktop.txt"],
  }),
  c({
    id: "offline.app-replay-compaction",
    domain: "offline-contracts",
    surface: "settings",
    lane: "offline",
    necessary: true,
    preconditions: "vellum-eval 可建。",
    steps: "app-replay --suite canonical-compaction-12",
    expected: "通過。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/app-replay-compaction.txt"],
  }),
  c({
    id: "offline.enhanced-gate-status",
    domain: "offline-contracts",
    surface: "enhanced",
    lane: "offline",
    necessary: true,
    preconditions: "scripts/enhanced-gate.mjs 可用。",
    steps: "node scripts/enhanced-gate.mjs status",
    expected: "讀取狀態成功（不要求本機已武裝 live core）。",
    verificationSources: ["command-log"],
    automation: "shell",
    evidence: ["logs/enhanced-gate-status.txt"],
  }),
  c({
    id: "offline.official-passthrough",
    domain: "offline-contracts",
    surface: "models",
    lane: "offline",
    necessary: true,
    preconditions: "契約測試與 protocol replay。",
    steps: "涵蓋 Official Responses 原生 passthrough（不經第三方 Chat／Responses 轉譯）。",
    expected: "相關 cargo／replay 通過。本輪不做付費 Official live。",
    verificationSources: ["protocol-replay", "proxy-runtime-tests"],
    automation: "shell",
    evidence: ["logs/official-passthrough.txt"],
  }),
  c({
    id: "offline.cross-provider-isolation",
    domain: "offline-contracts",
    surface: "models",
    lane: "offline",
    necessary: true,
    preconditions: "契約測試。",
    steps: "驗證不轉送 opaque Official reasoning／未物化 foreign compaction。",
    expected: "隔離測試通過。",
    verificationSources: ["proxy-runtime-tests", "adapter-tests"],
    automation: "shell",
    evidence: ["logs/cross-provider-isolation.txt"],
  }),
  c({
    id: "offline.streaming",
    domain: "offline-contracts",
    surface: "log",
    lane: "offline",
    necessary: true,
    preconditions: "stream fixtures。",
    steps: "streaming 契約／parity。",
    expected: "通過。",
    verificationSources: ["proxy_runtime_parity", "protocol-replay"],
    automation: "shell",
    evidence: ["logs/streaming.txt"],
  }),
  c({
    id: "offline.continuation-compaction",
    domain: "offline-contracts",
    surface: "context",
    lane: "offline",
    necessary: true,
    preconditions: "canonical compaction replay。",
    steps: "continuation／compaction 契約。",
    expected: "通過。",
    verificationSources: ["app-replay", "proxy-runtime-tests"],
    automation: "shell",
    evidence: ["logs/continuation-compaction.txt"],
  }),
  c({
    id: "offline.error-classification",
    domain: "offline-contracts",
    surface: "log",
    lane: "offline",
    necessary: true,
    preconditions: "provider 401／429／500 fixtures。",
    steps: "錯誤分類契約。",
    expected: "保留真實失敗類別，不換成泛用高需求訊息。",
    verificationSources: ["proxy_runtime_parity", "error.rs tests"],
    automation: "shell",
    evidence: ["logs/error-classification.txt"],
  }),
  c({
    id: "offline.official-live-not-run",
    domain: "offline-contracts",
    surface: "models",
    lane: "live",
    necessary: false,
    preconditions: "本輪政策：不新增付費 Official live 對照。",
    steps: "不發送 Official live。",
    expected: "結果固定 NOT_RUN；不得標 live-PASS。",
    verificationSources: ["policy"],
    automation: "none",
    evidence: ["policy.txt"],
    officialLive: true,
    defaultVerdict: "NOT_RUN",
  }),
];

const SANDBOX = [
  c({
    id: "sandbox.install.vellum-first",
    domain: "tabs",
    surface: "onboarding",
    lane: "sandbox",
    necessary: true,
    preconditions: "乾淨 Windows Sandbox；build-info 指定唯一 installer；Codex 尚未安裝。",
    steps: "先裝 Vellum，記錄 Codex 缺席，再裝 Codex。",
    expected: "Vellum 安裝 exit 0；onboarding 顯示 Codex 缺席；版本與 SHA 符合 build-info。",
    verificationSources: ["installer-log", "process-list", "onboarding-ui"],
    automation: "sandbox-guest",
    evidence: ["install-log.json", "events.json"],
    driver: {
      prepare: "empty VM",
      action: { kind: "install", order: ["vellum", "codex"] },
      wait: { timeoutMs: 600000 },
      verify: { kind: "field-changed", field: "vellumInstalled" },
    },
  }),
  c({
    id: "sandbox.install.codex-first",
    domain: "tabs",
    surface: "onboarding",
    lane: "sandbox",
    necessary: true,
    preconditions: "第二個乾淨 VM；Codex 已裝。",
    steps: "先裝 Codex，再首次啟動 Vellum。",
    expected: "onboarding 偵測到 Codex；共用 IsolatedHome\\.codex。",
    verificationSources: ["install-log", "codex-home", "onboarding-ui"],
    automation: "sandbox-guest",
    evidence: ["install-log.json", "events.json"],
    driver: {
      prepare: "empty VM",
      action: { kind: "install", order: ["codex", "vellum"] },
      wait: { timeoutMs: 600000 },
      verify: { kind: "field-changed", field: "codexDetected" },
    },
  }),
  c({
    id: "sandbox.os.uninstall",
    domain: "tabs",
    surface: "settings",
    lane: "sandbox",
    necessary: true,
    preconditions: "破壞性案例；獨立 VM 或本輪最後執行。",
    steps: "卸載 Vellum。",
    expected: "Vellum.exe 消失；Proxy 不在；exit code 記錄在案。",
    verificationSources: ["process-list", "filesystem"],
    automation: "sandbox-guest",
    evidence: ["uninstall-log.json", "events.json"],
    driver: {
      prepare: "Vellum installed",
      action: { kind: "uninstall", control: "結束 Vellum", process: "Vellum" },
      wait: { timeoutMs: 120000 },
      verify: { kind: "process-stopped", name: "Vellum" },
    },
  }),
];

export const CASES = Object.freeze([
  ...TABS,
  ...ONBOARDING,
  ...DIALOGS,
  ...TRAY,
  ...INFO,
  ...ENHANCED_CORE,
  ...ENHANCED_TRAITS,
  ...REMOTE_MANAGER,
  ...SUBAGENTS,
  ...GUARDIAN,
  ...OFFLINE,
  ...SANDBOX,
]);

export const MATRIX = Object.freeze({
  version: MATRIX_VERSION,
  passClaim: PASS_CLAIM,
  requiredTabs: REQUIRED_TABS,
  requiredSurfaces: REQUIRED_SURFACES,
  requiredDomains: REQUIRED_DOMAINS,
  verdicts: VERDICTS,
  cases: CASES,
});

export function casesForLane(lane) {
  if (lane === "all") return CASES;
  if (lane === "desktop") {
    return CASES.filter((item) => item.lane === "desktop" || item.lane === "offline");
  }
  return CASES.filter((item) => item.lane === lane);
}
