# A disposable Linux deployment target for Remote Manager development.
#
# `up` boots a container that satisfies the three host preconditions Remote
# Manager checks (Docker, user systemd, linger), publishes SSH, and writes a
# marked `Host vellum-dev-host` block into ~/.ssh/config so both `ssh` and
# Vellum Desktop's own host discovery can see it. `reset` throws the host
# away and boots a pristine one, which is what the clean-host path needs.
[CmdletBinding()]
param(
    [ValidateSet("up", "down", "reset", "status", "ssh", "print-alias")]
    [string] $Command = "up",
    [int] $Port = 22222,
    [switch] $Rebuild,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]] $Rest
)

$ErrorActionPreference = "Stop"
$utf8 = New-Object System.Text.UTF8Encoding($false)
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

$repo = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$image = "vellum-dev-host:latest"
$container = "vellum-dev-host"
$alias = "vellum-dev-host"
$stateRoot = Join-Path $repo "target\dev-host"
$keyPath = Join-Path $stateRoot "id_dev_host"
$knownHosts = Join-Path $stateRoot "known_hosts"
$sshConfigFragment = Join-Path $stateRoot "ssh_config"
$userSshConfig = Join-Path $HOME ".ssh\config"
$beginMarker = "# BEGIN vellum-dev-host (generated by scripts/dev-host.ps1)"
$endMarker = "# END vellum-dev-host"

function Require-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker Desktop is required to run the dev host"
    }
}

function Container-State {
    $state = docker inspect -f '{{.State.Status}}' $container 2>$null
    if ($LASTEXITCODE -ne 0) { return "absent" }
    return $state.Trim()
}

function Ensure-Image {
    $exists = docker image inspect $image 2>$null
    if ($Rebuild -or $LASTEXITCODE -ne 0) {
        Write-Host "==> Building $image"
        docker buildx build --load -t $image -f (Join-Path $repo "deploy\dev-host\Dockerfile") (Join-Path $repo "deploy\dev-host")
        if ($LASTEXITCODE -ne 0) { throw "dev host image build failed" }
    }
}

function Ensure-Key {
    New-Item -ItemType Directory -Force -Path $stateRoot | Out-Null
    if (-not (Test-Path -LiteralPath $keyPath)) {
        ssh-keygen -q -t ed25519 -N "" -C $alias -f $keyPath | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "ssh-keygen failed" }
    }
}

function Write-SshConfig {
    # A dedicated known_hosts, emptied on every boot: within one host lifetime
    # the key is verified normally, and a reset legitimately gets a new key
    # instead of being waved through by StrictHostKeyChecking=no.
    Remove-Item -LiteralPath $knownHosts -Force -ErrorAction SilentlyContinue
    $block = @(
        "Host $alias",
        "    HostName 127.0.0.1",
        "    Port $Port",
        "    User vellum",
        "    IdentityFile `"$keyPath`"",
        "    IdentitiesOnly yes",
        "    UserKnownHostsFile `"$knownHosts`"",
        "    StrictHostKeyChecking accept-new",
        "    BatchMode yes",
        ""
    ) -join "`n"
    [IO.File]::WriteAllText($sshConfigFragment, $block, $utf8)

    # The block goes into ~/.ssh/config verbatim rather than behind an Include:
    # Vellum's own host discovery scans that file's `Host` lines as raw text and
    # does not follow Include, so an included alias would work for `ssh` and be
    # invisible in Remote Manager.
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $userSshConfig) | Out-Null
    $existing = if (Test-Path -LiteralPath $userSshConfig) {
        [IO.File]::ReadAllText($userSshConfig, [Text.Encoding]::UTF8)
    } else { "" }
    $managed = "$beginMarker`n$block$endMarker`n"
    $startIndex = $existing.IndexOf($beginMarker)
    $endIndex = $existing.IndexOf($endMarker)
    if ($startIndex -ge 0 -and $endIndex -gt $startIndex) {
        $tail = $existing.Substring($endIndex + $endMarker.Length).TrimStart([char]13, [char]10)
        $updated = $existing.Substring(0, $startIndex) + $managed + $tail
    } else {
        $updated = $managed + "`n" + $existing
    }
    if ($updated -ne $existing) {
        [IO.File]::WriteAllText($userSshConfig, $updated, $utf8)
        Write-Host "==> Registered '$alias' in $userSshConfig (remove the marked block to undo)"
    }
}

function Wait-Systemd {
    $deadline = (Get-Date).AddSeconds(90)
    while ((Get-Date) -lt $deadline) {
        $state = (docker exec $container systemctl is-system-running 2>$null | Out-String).Trim()
        if ($state -eq "running" -or $state -eq "degraded") { return $state }
        Start-Sleep -Milliseconds 500
    }
    docker logs --tail 40 $container
    throw "dev host systemd did not come up within 90s"
}

function Wait-Ssh {
    $deadline = (Get-Date).AddSeconds(60)
    while ((Get-Date) -lt $deadline) {
        $probe = ssh -F $sshConfigFragment $alias 'docker info --format "{{.ServerVersion}}"' 2>$null
        if ($LASTEXITCODE -eq 0 -and $probe) { return }
        Start-Sleep -Milliseconds 500
    }
    docker logs --tail 40 $container
    throw "dev host SSH/dockerd did not become usable within 60s"
}

function Install-Key {
    $publicKey = [IO.File]::ReadAllText("$keyPath.pub", [Text.Encoding]::UTF8)
    $publicKey | docker exec -i $container tee /home/vellum/.ssh/authorized_keys | Out-Null
    docker exec $container chown vellum:vellum /home/vellum/.ssh/authorized_keys
    docker exec $container chmod 600 /home/vellum/.ssh/authorized_keys
    docker exec $container loginctl enable-linger vellum | Out-Null
}

function Show-Status {
    $state = Container-State
    if ($state -eq "absent") {
        Write-Host "dev host: absent (run: pnpm run dev:host:up)"
        return
    }
    $probe = ssh -F $sshConfigFragment $alias 'echo "uname=$(uname -m)"; echo "docker=$(docker info --format "{{.ServerVersion}}" 2>/dev/null)"; echo "userSystemd=$(XDG_RUNTIME_DIR=/run/user/1000 systemctl --user is-system-running 2>/dev/null)"; echo "linger=$(loginctl show-user vellum -p Linger --value)"; echo "agent=$(test -x ~/.local/bin/vellum-remote-agent && echo installed || echo absent)"' 2>&1
    Write-Host "dev host: $state  alias=$alias  ssh=127.0.0.1:$Port"
    $probe | ForEach-Object { Write-Host "  $_" }
}

switch ($Command) {
    "print-alias" { Write-Output $alias; break }

    "down" {
        Require-Docker
        docker rm -f -v $container 2>$null | Out-Null
        Write-Host "dev host removed"
        break
    }

    "status" {
        Require-Docker
        Show-Status
        break
    }

    "ssh" {
        if (-not $Rest -or $Rest.Count -eq 0) {
            ssh -F $sshConfigFragment $alias
        } else {
            ssh -F $sshConfigFragment $alias @Rest
        }
        exit $LASTEXITCODE
    }

    default {
        Require-Docker
        Ensure-Image
        Ensure-Key
        if ($Command -eq "reset" -or (Container-State) -ne "absent") {
            docker rm -f -v $container 2>$null | Out-Null
        }
        Write-Host "==> Booting $container on 127.0.0.1:$Port"
        # --privileged is what lets systemd and a nested dockerd run at all.
        # The tmpfs mounts keep /run out of the image layer, as on a real boot.
        #
        # The two anonymous volumes are what make the nested dockerd able to
        # *run* something rather than merely exist. This container's own root
        # is an overlay mount, and overlayfs cannot be stacked on overlayfs:
        # left in the image layer, the inner daemon's snapshots would fail at
        # `docker run` with `failed to mount ... fstype: overlay ... invalid
        # argument`. A volume is backed by the engine's real filesystem, so
        # the inner overlay has something it can actually stack on. Both
        # paths, because which one holds the snapshots depends on whether the
        # daemon uses the containerd image store or the classic graph driver.
        # This is the same reason the official dind image declares a volume
        # for /var/lib/docker.
        #
        # Anonymous, not named: they must live and die with this container, or
        # a reset would hand the next one somebody else's images. `docker rm`
        # below therefore passes -v.
        docker run -d --name $container --privileged `
            --publish "127.0.0.1:${Port}:22" `
            --tmpfs /run --tmpfs /run/lock `
            --volume /var/lib/docker --volume /var/lib/containerd `
            $image | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "failed to start dev host" }
        Write-SshConfig
        $systemState = Wait-Systemd
        Install-Key
        Wait-Ssh
        Write-Host "==> dev host ready (systemd: $systemState)"
        Show-Status
    }
}
